### ISSUE TITLE
Texture bools

### ISSUE THREAD

**Issue by mwpzq8** [rdeioris/UnrealOnRPI4#7]
Hi!

I am just wanting to use this to play around and got through all the code but can't find the texture bools in my project setting/platforms/Linux section. Is this where I should find them? I added the code in Visual Studio and did 'Rebuild Solution' on the solution. 

I'm assuming that this code gives you the actual bools in the project settings? 

\UE_4.26\Engine\Source\Developer\Linux\LinuxTargetPlatform\Classes\LinuxTargetSettings.h
```
        UPROPERTY(EditAnywhere, config, Category = Textures, meta = (DisplayName = "Cook DXT Textures"))
	bool bCookDXTTextures;
	
	UPROPERTY(EditAnywhere, config, Category = Textures, meta = (DisplayName = "Cook BC Textures"))
	bool bCookBCTextures;
	
	UPROPERTY(EditAnywhere, config, Category = Textures, meta = (DisplayName = "Cook ETC2 Textures"))
	bool bCookETC2Textures;
```

This is my first time making changes to the engine so I assume I did something wrong. From another comment I think I have to build the engine from source I'm guessing.

Thanks, 
Mark

**Comment by rdeioris** [comment]
Hi @mwpzq8 you need to manually add them in the file (so they will be shown in the settings)

**Comment by mwpzq8** [comment]
> Hi @mwpzq8 you need to manually add them in the file (so they will be shown in the settings)

So you do not need to build the engine from source?

**Comment by mwpzq8** [comment]
Okay thank I got it working! I had to build from source =)

**Comment by mwpzq8** [comment]
At first it seems like Unreal is to heavy to run on the Pi but you can get 30 fps or more depending on your settings. Set your base Desktop screen resolution to 800x600 and then set your r.screenpercentage accordingly from 1 to 100 in the unreal engine command line if you want more fps.
